[project]
name = "scottbrian_throttle"
version = "1.0.0"
description = "Miscellaneous utilities"
readme = "README.rst"
requires-python = "~=3.14.0"
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["utilities"]
authors = [{ name = "Scott Tuttle", email = "sbtuttle@outlook.com" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Recovery Tools",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Operating System :: Microsoft :: Windows :: Windows 11"]
dependencies = [
    "pydantic ~=2.13",
    "sentry-sdk ~=2.69",
    "scottbrian-locking ~=3.0",
    "scottbrian-utils ~=7.1",
    "wrapt ~=2.4",
    "tox>=4.64.1",
]

#[tool.setuptools]
#packages = ["scottbrian_throttle"]
#package-dir = { "" = "src" }

[tool.mypy]
mypy_path = "typings"


[project.urls]
Documentation = "https://scottbrian-throttle.readthedocs.io/en/latest/"
Source = "https://github.com/ScottBrian/scottbrian_throttle.git"

#[build-system]
#requires = ["setuptools ~=83.0"]
#build-backend = 'setuptools.build_meta'

[build-system]
requires = ["hatchling"]
build-backend = 'hatchling.build'

# Ensure your py.typed marker and Mypy plugin are included in the build
[tool.hatch.build.targets.wheel]
packages = ["src/scottbrian_throttle"]
